blank_issues_enabled: false
contact_links:
  - name: ⚛️ React Native Issues
    url: https://github.com/facebook/react-native/issues
    about: Please report bugs or issues in the React Native repository.
